name: Nexus

resources:
 repositories:
 - repository: self
   checkoutOptions:
    submodules: true

trigger:
 branches:
  include:
  - master
  - development

jobs:
- job: "Nexus Windows Build"
  pool:
   vmImage: 'windows-latest'

  steps:
  - task: BatchScript@1
    inputs:
     filename: "GenerateProjectFiles.bat"

  - task: MSBuild@1
    inputs:
     solution: "Nexus.sln"
     msbuildVersion: "latest"
     msbuildArchitecture: "x64"
     configuration: "Debug"

  - task: MSBuild@1
    inputs:
     solution: "Nexus.sln"
     msbuildVersion: "latest"
     msbuildArchitecture: "x64"
     configuration: "Release"

  - task: MSBuild@1
    inputs:
     solution: "Nexus.sln"
     msbuildVersion: "latest"
     msbuildArchitecture: "x64"
     configuration: "Distribution"

- job: "Nexus Linux Build"
  pool:
   vmImage: "ubuntu-latest"

  steps:
  - task: ShellScript@2
    inputs:
     scriptPath: "Setup.sh"

  - task: ShellScript@2
    inputs:
     scriptPath: "GenerateProjectFiles.sh"

  - task: Bash@3
    inputs:
     targetType: "inline"
     script: "make Debug"

  - task: Bash@3
    inputs:
     targetType: "inline"
     script: "make Release"

  - task: Bash@3
    inputs:
     targetType: "inline"
     script: "make Distribution"