name: Nexus

resources:
 repositories:
 - repository: self
   checkoutOptions:
    submodules: true

trigger:
 branches:
  include:
  - master
  - development
  - feature/*

jobs:
- job: Windows
  pool:
   vmImage: 'windows-latest'

  steps:
  - task: BatchScript@1
    displayName: Generate Project Files
    inputs:
     filename: "GenerateProjectFiles.bat"

  - task: MSBuild@1
    displayName: Debug Build
    inputs:
     solution: "Nexus.sln"
     msbuildVersion: "latest"
     msbuildArchitecture: "x64"
     configuration: "Debug"

  - task: MSBuild@1
    displayName: Release Build
    inputs:
     solution: "Nexus.sln"
     msbuildVersion: "latest"
     msbuildArchitecture: "x64"
     configuration: "Release"

  - task: MSBuild@1
    displayName: Distribution Build
    inputs:
     solution: "Nexus.sln"
     msbuildVersion: "latest"
     msbuildArchitecture: "x64"
     configuration: "Distribution"

- job: Linux
  pool:
   vmImage: "ubuntu-latest"

  steps:
  - task: ShellScript@2
    displayName: Setup
    inputs:
     scriptPath: "Setup.sh"

  - task: ShellScript@2
    displayName: Generate Project Files
    inputs:
     scriptPath: "GenerateProjectFiles.sh"

  - task: Bash@3
    displayName: Debug Build
    inputs:
     targetType: "inline"
     script: "make config=debug"

  - task: Bash@3
    displayName: Release Build
    inputs:
     targetType: "inline"
     script: "make config=release"

  - task: Bash@3
    displayName: Distribution Build
    inputs:
     targetType: "inline"
     script: "make config=distribution"

  - job: Mac
    pool: 
     vmImage: "macOS-latest"

    steps:
    - task: ShellScript@2
      displayName: Setup
      inputs:
       scriptPath: "Setup.command"

    - task: ShellScript@2
      displayName: Generate Project Files
      inputs:
       scriptPath: "GenerateProjectFiles.command"

    - task: Xcode@5
      inputs:
       actions: 'build'
       scheme: ''
       sdk: "macos"
       configuration: "Debug"
       xcWorkspacePath: "**/*.xcodeproj/project.xcworkspace"
       xcodeVersion: "default"
       signingOption: "default"
       useXcpretty: "false"

