
name: Nexus

resources:
 repositories:
 - repository: self
   checkoutOptions:
    submodules: true

trigger:
- master

jobs:
- job: Nexus
  pool:
   vmImage: 'windows-latest'

  steps:
  - task: InstallSSH@Key0
    inputs:
     knownHostsEntry: "github.com"
     sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCVVBHdkU4kCC7HvN9tYO9kVaJjO3YHLiITCIa7+KDLzL6gJmSALeSu/dVrXXMclkkmJCzaNT8UCiKcXThib0zWSYT7KpiDULZgy93TbM155g3J5sFhAia3onaioyPLXNVO4gVjBwdWNsYrGKhlvMHad6eiO3PmUB+aI4LZfkybZV5GiFCUEAVCWhSQqZB4kwwRRVwosg0A34ulLRzG+0BiFBfkNM1/WHYPLbthZDgWX05UP28M7uvV8dTBTuGVQZsfK+Zz70Lx05tmdJbBmx2xvWpd6n+93wi4le+iYeAmnnRfbEzijRaLoU5upKBfvp7qtzSiA6T7X636Or/hQHYH"
     sshKeySecureFile: "gitkraken_rsa"

  - task: BatchScript@1
    inputs:
     filename: "GenerateProjectFiles.bat"

  - task: MSBuild@1
    inputs:
     solution: "Nexus.sln"
     msbuildVersion: "latest"
     msbuildArchitecture: "x64"
     configuration: "Distribution"









